### ISSUE TITLE
Using flutter's Android View: a rewrite is needed!

### ISSUE THREAD

**Issue by RNMBuser** [mapbox/flutter-mapbox-gl#59]
Hi @tobrun and everyone!

There seams to be a development on the flutter team: You can now [embed an Android view in the Widget hierarchy](https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/AndroidView-class.html)! Soon, the same will be possible on iOS too.

I think this call for a rewrite of this plugin. A [Google Maps plugin](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter) is being developed.

**Comment by tobrun** [comment]
@RNMBuser this great to hear! 
This would unblock iOS integration and would make maintenance a lot easier!

**Comment by g123k** [comment]
Be careful the AndroidView only supports API 20+
Flutter is working with 16+ devices

**Comment by tobrun** [comment]
Thanks for the ping @g123k , after looking at the documentation I'm also not convinced this will be the way forward: `Embedding Android views is an expensive operation and should be avoided when a Flutter equivalent is possible.`, We are able to use a Flutter equivalent and it feels faster as the Android SDK equivalent.

**Comment by runarj** [comment]
This [article](https://medium.com/flutter-community/flutter-platformview-how-to-create-flutter-widgets-from-native-views-366e378115b6) gives details on the new widget.

Another possibility would of course be to draw all tiles using Flutter and Dart itself, and not rely on external views. If I am not mistaken, this is how Mapbox works on JavaScript. A Dart implementation could have some advantages, like true portability to new platforms, and extensibility. Is this a route you have considered, or is it too expensive?

**Comment by yoavrofe** [comment]
Of course embedding an Android view is an expensive operation, **in comparison to a flutter view**!

MapBox is a complex framework, that cannot be compared in any way to a simple button. Moreover, using a flutter view, as in the current implementation, requires quite a lot of coding, since many things, such as gestures, would need to be implemented. In order for it to have full functionality, we will have to rewrite MapView from scratch in dart. User location is another problem, and more code will be needed for that. Regarding the API 20+ issue, this would probably be possible in [API 19+ in some time](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/platform/VirtualDisplayController.java#L82).

In the far future (late 2019/2020), I believe that dart/flutter should be supported as a platform using C++ interop, possibly [in this method](https://github.com/flutter/flutter/issues/7053#issuecomment-415161464). This, however, will require a lot of coding and time investment. C++ interop is not possible yet in dart, but may be possible in the future.

Using an Android (and soon an iOS) view is the most straightforward way to support MapBox. This is a pretty simple, and this is the selected way by the Google team for supporting [Google Maps](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter), and also webview in the near future. This is why I believe this is currently the best and fastest way to go.

**Comment by tobrun** [comment]
This landed as part of #71, thank you @yoavrofe for this contribution!
